name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # You can specify other versions as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pillow opencv-python-headless  # Install required packages

    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py"
